name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWD }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: dylanbekers/pe-frontend
      - name: Sent post request to Portainer Service Webhook
        uses: jasongitmail/fast-webhook@v1
        with:
          url: ${{ secrets.WEBHOOK_URL }}
          json: '{}'
